# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OBFU' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OBFU
  # pod 'PromiseKit', '6.18.1'
  # pod 'CryptoSwift', '1.4.2'

end
